spring:
  profiles:
    active: dev
  application:
    name: movkfact

logging:
  level:
    root: INFO
    com.movkfact: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
