package com.movkfact.entity;

import jakarta.persistence.*;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import java.time.LocalDateTime;

/**
 * JPA Entity representing a data domain in movkfact.
 *
 * Domains are the top-level organizational unit where datasets and data generation
 * activities are grouped. Each domain has unique metadata including creation timestamps
 * and soft-delete support via deletedAt flag.
 *
 * Soft Delete Pattern: This entity supports logical deletion via the deletedAt field.
 * Use findByDeletedAtIsNull() when querying active domains only.
 *
 * Optimistic Locking: The version field prevents race conditions on concurrent updates.
 * JPA automatically manages version increments on each save operation.
 *
 * Performance: Database indexes on name and deleted_at columns optimize query performance
 * for common operations like case-insensitive name lookups and soft-delete filtering.
 *
 * @author Amelia (Developer Agent)
 * @version 1.0
 */
@Entity
@Table(name = "domain_master", indexes = {
    @Index(name = "idx_domain_name", columnList = "name", unique = false),
    @Index(name = "idx_domain_deleted_at", columnList = "deleted_at")
})
public class Domain {

    /**
     * Unique identifier for the domain.
     * Auto-generated by the database on insert.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;

    /**
     * Version field for optimistic locking support.
     * Prevents race conditions on concurrent updates.
     * JPA automatically increments this field on each save operation.
     */
    @Version
    @Column(name = "version")
    private Long version;

    /**
     * The name/title of the domain.
     * Must be unique to prevent duplicate domain names in the system.
     * Cannot be null or empty (validated with @NotBlank).
     * Indexed for fast lookups in case-insensitive queries.
     */
    @Column(name = "name", nullable = false, unique = true, length = 255)
    @NotBlank(message = "Domain name is required and cannot be blank")
    @Size(min = 2, max = 255, message = "Domain name must be between 2 and 255 characters")
    private String name;

    /**
     * Optional description providing context about this domain's purpose.
     * Can be lengthy text, supports markdown formatting.
     * Nullable field, maximum 2000 characters for pragmatic storage balance.
     */
    @Column(name = "description", nullable = true, length = 2000)
    @Size(max = 2000, message = "Domain description must not exceed 2000 characters")
    private String description;

    /**
     * Timestamp when this domain was created.
     * Auto-populated on insert via @PrePersist callback, immutable afterward.
     * Set to current time at database level for consistency across servers.
     */
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;

    /**
     * Timestamp when this domain was last updated.
     * Auto-updated on every modification via @PreUpdate callback.
     * Refreshed to current time whenever entity is saved.
     */
    @Column(name = "updated_at", nullable = false)
    private LocalDateTime updatedAt;

    /**
     * Timestamp when this domain was soft-deleted (logically removed).
     * Nullable - only populated if domain is logically deleted.
     * Use findByDeletedAtIsNull() to query active domains exclusively.
     * Implemented for compliance with audit and data retention policies.
     * Indexed for performance on soft-delete filtering queries.
     */
    @Column(name = "deleted_at", nullable = true)
    private LocalDateTime deletedAt;

    // ========== Constructors ==========

    /**
     * No-argument constructor required by JPA.
     * Used by Hibernate during object instantiation from database rows.
     */
    public Domain() {
    }

    /**
     * Constructor with name and description.
     * Timestamps are set by @PrePersist callback on first persist.
     * Version is initialized to null (managed by JPA on insert).
     *
     * @param name The domain name (non-blank, 2-255 chars)
     * @param description Optional domain description (max 2000 chars)
     */
    public Domain(String name, String description) {
        this.name = name;
        this.description = description;
        this.deletedAt = null;
        this.version = null;
    }

    /**
     * Constructor with name only.
     * Description defaults to null.
     *
     * @param name The domain name (non-blank, 2-255 chars)
     */
    public Domain(String name) {
        this(name, null);
    }

    // ========== Lifecycle Callbacks ==========

    /**
     * JPA callback to initialize timestamps on first insert.
     * Called by JPA before INSERT operation.
     * Sets both createdAt and updatedAt to current time.
     */
    @PrePersist
    protected void onCreate() {
        LocalDateTime now = LocalDateTime.now();
        if (createdAt == null) {
            createdAt = now;
        }
        if (updatedAt == null) {
            updatedAt = now;
        }
    }

    /**
     * JPA callback to update the modified timestamp on every update.
     * Called by JPA before UPDATE operation.
     * Refreshes updatedAt but leaves createdAt unchanged (immutable).
     */
    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // ========== Getters & Setters ==========

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Long getVersion() {
        return version;
    }

    public void setVersion(Long version) {
        this.version = version;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public LocalDateTime getCreatedAt() {
        return createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    public LocalDateTime getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    public LocalDateTime getDeletedAt() {
        return deletedAt;
    }

    public void setDeletedAt(LocalDateTime deletedAt) {
        this.deletedAt = deletedAt;
    }

    // ========== Utility Methods ==========

    /**
     * Checks if this domain is logically deleted.
     * Safe method to test soft-delete status without null checks.
     *
     * @return true if deletedAt is not null, false otherwise
     */
    public boolean isDeleted() {
        return deletedAt != null;
    }

    /**
     * Marks this domain as soft-deleted by setting deletedAt to current time.
     * Does not immediately persist to database - caller must call repository.save().
     * Allows reversal via restore() method before save.
     */
    public void softDelete() {
        this.deletedAt = LocalDateTime.now();
    }

    /**
     * Restores a soft-deleted domain by clearing the deletedAt timestamp.
     * Does not immediately persist to database - caller must call repository.save().
     * Reverses previous softDelete() call.
     */
    public void restore() {
        this.deletedAt = null;
    }

    // ========== Object Overrides ==========

    @Override
    public String toString() {
        return "Domain{" +
                "id=" + id +
                ", version=" + version +
                ", name='" + name + '\'' +
                ", description='" + (description != null ? description.substring(0, Math.min(50, description.length())) + "..." : "null") + '\'' +
                ", createdAt=" + createdAt +
                ", updatedAt=" + updatedAt +
                ", deletedAt=" + deletedAt +
                ", isDeleted=" + isDeleted() +
                '}';
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Domain)) return false;
        Domain domain = (Domain) o;
        return id != null && id.equals(domain.id);
    }

    @Override
    public int hashCode() {
        return id != null ? id.hashCode() : 0;
    }
}
